name: 'composite action'
runs:
  using: 'composite'
  steps:
    - name: "download artifact"
      uses: actions/download-artifact@v4
      with: 
        name: drop
        path: drop
    - name: "check dir"
      shell: bash
      run: |
        ls