name: Create Release

on:
  workflow_dispatch:
    inputs:
      releaseversion:
        description: "pass release version in v*.*.* format"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "version ${{github.event.inputs.releaseversion}}"
