name: Semantic release
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.8.1
      - name: Install dependencies
        run: npm ci
      - name: End message
        run: echo 'Dependencies installed'
      - name: Initialize Git User
        run: |
          git config --global user.email "placzkowskim@hotmail.com"
          git config --global user.name "Release Workflow"
      - name: Run release with semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
