name: Relase-it
on:
  workflow_dispatch:
    inputs:
      releaseversion:
        description: "pass release version in *.*.* format"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: End message
        run: echo 'Dependencies installed'
      - name: Initialize Git User
        run: |
          git config --global user.email "placzkowskim@hotmail.com"
          git config --global user.name "Release Workflow"
      - name: Run release
        run: npx release-it ${{github.event.inputs.releaseversion}} --ci
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
