name: Create Release

on:
  workflow_dispatch:
    inputs:
      releaseversion:
        description: "pass release version in v*.*.* format"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: echo version
        run: echo "version ${{github.event.inputs.releaseversion}}"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: run status
        run: git branch --show-current
